### ISSUE TITLE
Габариты

### ISSUE THREAD

**Issue by Nadezhda-n** [rusefi/proteus-mustang5.0-60-pin#3]
На плате заданы габариты 5.5 in * 6.5 in, при этом используется не все пространство (внизу пусто), мне туда и ставить модуль can или расширять?

**Comment by rusefillc** [comment]
хороший вопрос! сегодня уточню, будем ли делать вот так:

![image](https://user-images.githubusercontent.com/48498823/168478927-7620ce1c-dca4-422c-a261-006692b303c6.png)

**Comment by rusefillc** [comment]
Давай сделаем как на моей картинке - повернём один на 180 градусов и увеличим плату снизу?

**Comment by Nadezhda-n** [comment]
А что за линии снищу, будто она уже увеличена? 
Мне это игнорировать?

**Comment by rusefillc** [comment]
не понимаю про линии. идея в том, чтоб увеличить снизу в разумных объёмах - без кучи лишнего свободного места
