### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-mustang5.0-60-pin#6]
even with #5 create board step has failed

@andreika-git please advice

**Comment by andreika-git** [comment]
Maybe this one would help?
![image](https://user-images.githubusercontent.com/15104768/170426990-aef141e7-aeea-43a3-b207-17cd915b0177.png)

**Comment by rusefillc** [comment]
@Nadezhda-n please adjust ^^^. Возможно нужно будет подвинуть origin marker, чтоб всё было в положительной области

и новый экспорт по той же инструкции плиз.

**Comment by Nadezhda-n** [comment]
![Screenshot_20220526_202039_com.yandex.browser.jpg](https://user-images.githubusercontent.com/99179773/170541600-b46c8e2c-59fc-40eb-9c70-3817fe6749e8.jpg)

**Comment by Nadezhda-n** [comment]
@andreika-git
Это может быть из-за того, что точка начала координат стала с отрицательной коррдинатой (в абсолюте)? 
Больше ничего не менялось

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/170662111-6a98f13d-c3d0-4841-8717-59fca929235e.png)

The 'hellen-one' submodule has been changed in the latest commit. Currently it points to the "Apr,14" version (which is really old). Please revert it and use only the latest version of hellen-one.

**Comment by rusefillc** [comment]
@andreika-git я вернул hellen-one новейший, но всё равно не работает

**Comment by Nadezhda-n** [comment]
Все же сдвинула всю плату в положительную область

![image](https://user-images.githubusercontent.com/99179773/170856106-a8ce0111-484c-4950-ab1d-d10d4475995d.png)
