### ISSUE TITLE
modules are offset both on preview and gerbers

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-mustang5.0-60-pin#7]
![image](https://user-images.githubusercontent.com/48498823/171652913-f23dd525-1168-4571-afc2-b15474908210.png)

![image](https://user-images.githubusercontent.com/48498823/171652678-4dfeb40d-8f06-459b-be1b-0b92a6b22633.png)

**Comment by rusefillc** [comment]
@andreika-git need your advice here, what have we missed?

Is any validation of this issue possible? Would it be trivial or not?

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/171659353-a5b04582-5acb-4339-9ac6-b96560736253.png)

1) Check the outline of the frame ("Edge.Cuts" should contain the closed line shape)
2) Check the "origin" - it should match the coordinates of the left bottom corner of the frame outline

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/172180451-7b393a8e-90df-4ff0-b5e5-37ac63fb2fe9.png)
![image](https://user-images.githubusercontent.com/99179773/172180491-b55c333d-4884-44d4-9209-86f5d7776d40.png)

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/172188461-61b976b1-7ab5-448f-97c3-5b775fe0ac07.png)

This is not origin. The origin is not set!

That's the origin (the red one):

![image](https://user-images.githubusercontent.com/15104768/172188541-b1df1fd7-0564-4625-bb34-b8d883c5e3d7.png)

As I already told you, you must set the origin:

**Comment by Nadezhda-n** [comment]
Для меня это сейчас стало открытием, спасибо.
Дело именно в этом.
Чуть позже исправлю
